sudo: required
services:
- docker
language: bash

before_install:  
  - sudo apt-get remove docker docker-engine
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get install docker-ce

script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset

# Call build mosquitto
- cd mosquitto && ./build-mosquitto.sh && cd $TRAVIS_BUILD_DIR

# Call build alpine
- cd alpine && ./build-alpine.sh && cd $TRAVIS_BUILD_DIR

# Call build Node
- cd node && ./build-node.sh && cd $TRAVIS_BUILD_DIR

# Call build node-red
- cd node-red && ./build-node-red.sh && cd $TRAVIS_BUILD_DIR